parcial/config/routes.rb
Parcial::Application.routes.draw do
  resources :especialidads

  resources :medicos
  get "static/home"

   root 'medicos#index'

end

parcial/app/models/especialidad.rb
class Especialidad < ActiveRecord::Base

		has_many :medicos
end

parcial/app/models/medico.rb
class Medico < ActiveRecord::Base
		belongs_to :especialidad
end

parcial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

parcial/app/controllers/especialidads_controller.rb
class EspecialidadsController < ApplicationController
  before_action :set_especialidad, only: [:show, :edit, :update, :destroy]

  # GET /especialidads
  # GET /especialidads.json
  def index
    @especialidads = Especialidad.all
  end

  # GET /especialidads/1
  # GET /especialidads/1.json
  def show
  end

  # GET /especialidads/new
  def new
    @especialidad = Especialidad.new
  end

  # GET /especialidads/1/edit
  def edit
  end

  # POST /especialidads
  # POST /especialidads.json
  def create
    @especialidad = Especialidad.new(especialidad_params)

    respond_to do |format|
      if @especialidad.save
        format.html { redirect_to @especialidad, notice: 'Especialidad was successfully created.' }
        format.json { render action: 'show', status: :created, location: @especialidad }
      else
        format.html { render action: 'new' }
        format.json { render json: @especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidads/1
  # PATCH/PUT /especialidads/1.json
  def update
    respond_to do |format|
      if @especialidad.update(especialidad_params)
        format.html { redirect_to @especialidad, notice: 'Especialidad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidads/1
  # DELETE /especialidads/1.json
  def destroy
    @especialidad.destroy
    respond_to do |format|
      format.html { redirect_to especialidads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidad
      @especialidad = Especialidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especialidad_params
      params.require(:especialidad).permit(:nombre)
    end
end

parcial/app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy, :list]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new

  end

  # GET /medicos/1/edit
  def edit
  end
  
  def list
    @medicos = Medico.all

  end  

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)
      @especialidads = Especialidad.all
    respond_to do |format|
      if @medico.save
      
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medico }
      else
        format.html { render action: 'new' }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
      
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
      @especialidads = Especialidad.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nombres, :apellidos, :celular, :email, :curriculum, :reconocimientos, :especialidad_id)
    end
end

parcial/app/helpers/application_helper.rb
module ApplicationHelper
end

parcial/app/helpers/especialidads_helper.rb
module EspecialidadsHelper
end

parcial/app/helpers/medicos_helper.rb
module MedicosHelper
end

parcial/app/views/especialidads/_form.html.erb
<%= form_for(@especialidad) do |f| %>
  <% if @especialidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@especialidad.errors.count, "error") %> prohibited this especialidad from being saved:</h2>

      <ul>
      <% @especialidad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

parcial/app/views/especialidads/edit.html.erb
<h1>Editing especialidad</h1>

<%= render 'form' %>

<%= link_to 'Show', @especialidad %> |
<%= link_to 'Back', especialidads_path %>

parcial/app/views/especialidads/index.html.erb
<h1>Listing especialidads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @especialidads.each do |especialidad| %>
      <tr>
        <td><%= especialidad.nombre %></td>
        <td><%= link_to 'Show', especialidad %></td>
        <td><%= link_to 'Edit', edit_especialidad_path(especialidad) %></td>
        <td><%= link_to 'Destroy', especialidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especialidad', new_especialidad_path %>

parcial/app/views/especialidads/new.html.erb
<h1>New especialidad</h1>

<%= render 'form' %>

<%= link_to 'Back', especialidads_path %>

parcial/app/views/especialidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @especialidad.nombre %>
</p>

<%= link_to 'Edit', edit_especialidad_path(@especialidad) %> |
<%= link_to 'Back', especialidads_path %>

parcial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Tercer Parcial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  	<link rel="stylesheet" type="text/css" href="base.css">

</head>
<body>


<%= yield %>

</body>
</html>

parcial/app/views/layouts/list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parcial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<table border="1">
 <tr>
  <td width="80%"><p align="center"><i><b>nombre</b></i></td>
  <td width="20%"><p align="center"><i><b>apellido</b></i></td>
 </tr>


<%= yield %>

</body>
</html>

parcial/app/views/medicos/_form.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %><br>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.number_field :celular %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :curriculum %><br>
    <%= f.text_area :curriculum %>
  </div>
  <div class="field">
    <%= f.label :reconocimientos %><br>
    <%= f.text_area :reconocimientos %>
  </div>

    <div class="field">

<%= f.label :especialidad %>
</br>
  <select name="medico[especialidad_id]">
   <% @especialidads.each do |especialidad| %>
       <option value="<%= especialidad.id %>" 
         <%= ' selected' if especialidad.id == @medico.especialidad_id %>>
         <%= especialidad.nombre %>
       </option>
   <% end %>
  </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

parcial/app/views/medicos/_form1.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %><br>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.number_field :celular %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :curriculum %><br>
    <%= f.text_area :curriculum %>
  </div>
  <div class="field">
    <%= f.label :reconocimientos %><br>
    <%= f.text_area :reconocimientos %>
  </div>


  <div class="field">
    <%= f.label :especialidad_id %><br>
    <%= f.number_field :especialidad_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

parcial/app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

parcial/app/views/medicos/index.html.erb
	<div id="cabecera">
		<div id="titulocabecera">
			<h1>Gestión Doctores</h1>
		</div>
	</div>
	
	<div id="contenedor">

		<div id="boxizquierda">
			<div id="boxmenu">
				<ul class="menu">
					<li><a href="#">Home</a></li>
					<li><%= link_to 'Nuevo Medico', new_medico_path %></li>
			
				</ul>
			</div>	
		</div>	
			<table border="1">
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Curriculum</th>
      <th>Reconocimientos</th>
      <th>Especialidad</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= link_to medico.nombres, :action => "show", :id =>  medico.id %></td>
        <td><%= medico.apellidos %></td>
        <td><%= medico.celular %></td>
        <td><%= medico.email %></td>
        <td><%= medico.curriculum %></td>
        <td><%= medico.reconocimientos %></td>
        <td><%= medico.especialidad.nombre %></td>
        <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destroy', medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
		

	<div id="footer">
		<div class="texto">
			Clínica Sabanera. Autopista Norte Km 6 | Tel: (571) 8614545
			</br>
			</br>
			<a href="mailto:clisaba@unisabana.co">contacto: clisaba@unisabana.co</a>
		</div>	
	</div>
	
	


<br>

parcial/app/views/medicos/list.html.erb
<head>
<title>Medicos</title>
</head>
<body>

<h1>Medicos</h1>
<table border="1">
 <tr>
  <td width="80%"><p align="center"><i><b>nombre</b></i></td>
  <td width="20%"><p align="center"><i><b>apellido</b></i></td>
 </tr>

 <% @medicos.each do |medico| %>
  <tr>
   <td><%= link_to medico.edit, :action => "show", :id => medico.id %></td>
   <td><%= medico.nombres %></td>
  </tr>
 <% end %>
</table>
<p><%= link_to "Craer un nuevo medico", :action => "new" %></p>

</body>

parcial/app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render 'form1' %>

<%= link_to 'Back', medicos_path %>

parcial/app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @medico.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @medico.apellidos %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @medico.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @medico.email %>
</p>

<p>
  <strong>Curriculum:</strong>
  <%= @medico.curriculum %>
</p>

<p>
  <strong>Reconocimientos:</strong>
  <%= @medico.reconocimientos %>
</p>

<p>
  <strong>Especialidad:</strong>
<%= @medico.especialidad.nombre %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>